
FROM nginx:latest

WORKDIR app

COPY app/ app/

RUN apt-get update

RUN apt -y install python3.8

RUN apt-get -y install python3-pip


RUN pip install -r /app/requirements.txt

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy your Nginx configuration file
COPY nginx/nginx.conf /etc/nginx/conf.d/

# Expose port 80
EXPOSE 80

CMD ["python", "app.py"] 
